### ISSUE TITLE
Name not valid error

### ISSUE THREAD

**Issue by amad-haseeb** [iamazeem/spdlog-vs-zlog#3]
Getting the following error on executing the binary after successful build.
```
[2024-02-06 07:13:15.731] [error] locale::facet::_S_create_c_locale name not valid
```

**Comment by iamazeem** [comment]
@amad-haseeb: Are you using the latest code?

**Comment by amad-haseeb** [comment]
Yes, cloned the repo about an hour ago.
Since the ``` git clone --recursive git@github.com:iamazeem/spdlog-vs-zlog.git ``` was not working, so used the links in ```.gitmodules``` to clone the repos. 

> @amad-haseeb: Are you using the latest code?

**Comment by iamazeem** [comment]
Please reclone it with the HTTPS URL. Fixed under #2.
LMK if you face the same issue again.
IIRC, the locale issue has already been fixed.

**Comment by amad-haseeb** [comment]
> Please reclone it with the HTTPS URL. Fixed under #2. LMK if you face the same issue again. IIRC, the locale issue has already been fixed.

Issue persist even after re-cloning.

**Comment by amad-haseeb** [comment]
> What's your OS and compiler version?


compiler: ```g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0```

OS: 
```Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by iamazeem** [comment]
Looks like a language configuration issue on your machine.
See https://stackoverflow.com/a/19114298/7670262.

Apparently, running this command should fix your issue:

```shell
sudo locale-gen en_US en_US.UTF-8
```

**Comment by amad-haseeb** [comment]
> Looks like a language configuration issue on your machine. See https://stackoverflow.com/a/19114298/7670262.
> 
> Apparently, running this command should fix your issue:
> 
> ```shell
> sudo locale-gen en_US en_US.UTF-8
> ```


Got this error ```sudo: locale-gen: command not found``` on executing this command.
Binary compiled successfully after installing ```locales``` and then executing the above command.
Thanks.
